import os


class GameContainerConfig:
    """
    Generates docker-compose.yml files for game servers, one file per game
    (mirrors EZarr's per-service container_configs pattern).

    Every game gets a method named after its key in main.py's GAMES dict and its
    badge-gated compose package under helper/<game>/ or a root-level <game>/
    folder (see main.py GAME_DIRS). Add a new method here when adding a new game.

    The generated compose files load settings from the shared repo-root `.env`
    (gitignored; generated by main.py - see example.env).
    """

    def __init__(self, root_dir):
        self.root_dir = root_dir

    def plutonium(self):
        cfg = f"{self.root_dir}/aio-plutonium-t6"
        return (
            "services:\n"
            "  aio-plutonium-t6:\n"
            "    image: ghcr.io/nw/aio-plutonium-t6:latest\n"
            "    container_name: aio-plutonium-t6-server\n"
            "    restart: unless-stopped\n"
            "    ports:\n"
            '      - "4976:4976/udp"   # game server port (host:guest/udp) - must match SERVER_PORT\n'
            '      - "4976:4976/tcp"   # RCON (Source/TCP) on the same port - used by switch-map.py\n'
            '      - "1624:1624/tcp"   # admin panel port (host:guest/tcp) - must match ADMIN_PORT\n'
            "    volumes:\n"
            f"      - {cfg}/plutonium:/t6server/plutonium\n"
            f"      - {cfg}/server/pluto_t6_full_game:/t6server/game_files:ro\n"
            f"      - {cfg}/server_data:/t6server/server\n"
            f"      - {cfg}/admin:/t6server/admin\n"
            f"      - {cfg}/updater:/t6server/updater\n"
            f"      - {cfg}/downloaded_files:/t6server/downloaded_files\n"
            f"      - {cfg}/status:/t6server/status\n"
            "    env_file:\n"
            "      - ../../.env   # shared repo-root .env (gitignored); generated by main.py - see example.env\n"
        )

    def satisfactory_server(self):
        cfg = f"{self.root_dir}/satisfactory-server"
        return (
            "services:\n"
            "  satisfactory-server:\n"
            "    image: wolveix/satisfactory-server:latest\n"
            "    container_name: satisfactory-server\n"
            "    restart: unless-stopped\n"
            "    ports:\n"
            '      - "7777:7777/udp"   # game server port (players connect here) - must match 7777\n'
            "    volumes:\n"
            f"      - {cfg}:/config\n"
            "    env_file:\n"
            "      - ../.env   # shared repo-root .env (gitignored); generated by main.py - see example.env\n"
        )
