import os


class GameContainerConfig:
    """
    Emits one docker-compose *service block* per game server (mirrors EZarr's
    per-service container_configs pattern). main.py merges the blocks for all
    selected games into a SINGLE repo-root docker-compose.yml (see main.py).

    Every game gets a method named after its key in main.py's GAMES dict
    (e.g. `plutonium_t6_zombies`, `satisfactory_server`). Add a new method here
    when adding a new game.

    The generated service blocks load settings from the shared repo-root .env
    via env_file (secrets/tokens are gitignored; generated by main.py - see
    example.env).
    """

    def __init__(self, root_dir):
        self.root_dir = root_dir

    def plutonium_t6_zombies(self):
        cfg = f"{self.root_dir}/aio-plutonium-t6"
        return f"""\
  aio-plutonium-t6-server:
    image: ghcr.io/nolanwinsman/aio-plutonium-t6:latest
    container_name: plutonium
    restart: unless-stopped
    ports:
      - "4976:4976/udp"   # game server port (host:guest/udp) - must match SERVER_PORT
      - "4976:4976/tcp"   # unused by game/RCON (T6 RCON is UDP on 4976); kept for parity - see docs/plutonium-t6-rcon.md
      - "1624:1624/tcp"   # admin panel port (host:guest/tcp) - must match ADMIN_PORT
    volumes:
      - {cfg}/plutonium:/t6server/plutonium
      - {cfg}/server/pluto_t6_full_game:/t6server/game_files:ro
      - {cfg}/server_data:/t6server/server
      - {cfg}/admin:/t6server/admin
      - {cfg}/updater:/t6server/updater
      - {cfg}/downloaded_files:/t6server/downloaded_files
      - {cfg}/status:/t6server/status
    env_file:
      - ./.env   # shared repo-root .env (gitignored); generated by main.py - see example.env
""".rstrip("\n")

    def satisfactory_server(self):
        cfg = f"{self.root_dir}/satisfactory-server"
        return f"""\
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    restart: unless-stopped
    ports:
      - "7777:7777/udp"   # game server port (players connect here)
      - "7777:7777/tcp"   # beacon/query port (server listing + client lookup)
      - "8888:8888/tcp"   # messaging port (server web console / backend)
    volumes:
      - {cfg}:/config
    env_file:
      - ./.env   # shared repo-root .env (gitignored); generated by main.py - see example.env
""".rstrip("\n")
